version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - ${SQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  wordpress:
    image: wordpress:5.8.1-apache
    container_name: wordpress
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./www:/var/www/html:rw
      - ./plugins:/var/www/html/wp-content/plugins:rw
      - ./themes:/var/www/html/wp-content/themes:rw
      - ./data/dump:/var/www/data:rw

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${ADMINER_PORT}:80
    depends_on:
      - db
